/**
 * Product entity interface
 *
 * Represents a product in the system with all its properties
 * including metadata like creation and update timestamps
 */
export interface Product {
  id: number;
  title: string;
  description: string;
  price: number;
  discountPercentage: number;
  rating: number;
  stock: number;
  brand: string;
  category: string;
  thumbnail: string;
  images: string[];
  createdAt: string;
  updatedAt: string;
}

/**
 * Request interface for creating a new product
 *
 * Omits the id, createdAt, and updatedAt fields as they are
 * generated by the system
 */
export interface CreateProductRequest {
  title: string;
  description: string;
  price: number;
  discountPercentage: number;
  rating: number;
  stock: number;
  brand: string;
  category: string;
  thumbnail: string;
  images: string[];
}

/**
 * Request interface for updating an existing product
 *
 * All fields are optional except id, and the id field is required
 * to identify which product to update
 */
export interface UpdateProductRequest extends Partial<CreateProductRequest> {
  id: number;
}

/**
 * User entity interface
 *
 * Represents a user in the system with comprehensive profile information
 * including personal details, address, company, and banking information
 */
export interface User {
  id: number;
  firstName: string;
  lastName: string;
  maidenName?: string;
  age: number;
  gender: "male" | "female" | "other";
  email: string;
  phone: string;
  username: string;
  password: string;
  birthDate: string;
  image: string;
  bloodGroup: string;
  height: number;
  weight: number;
  eyeColor: string;
  hair: {
    color: string;
    type: string;
  };
  domain: string;
  ip: string;
  address: {
    address: string;
    city: string;
    coordinates: {
      lat: number;
      lng: number;
    };
    postalCode: string;
    state: string;
  };
  macAddress: string;
  university: string;
  bank: {
    cardExpire: string;
    cardNumber: string;
    cardType: string;
    currency: string;
    iban: string;
  };
  company: {
    address: {
      address: string;
      city: string;
      coordinates: {
        lat: number;
        lng: number;
      };
      postalCode: string;
      state: string;
    };
    department: string;
    name: string;
    title: string;
  };
  ein: string;
  ssn: string;
  userAgent: string;
  createdAt: string;
  updatedAt: string;
}

/**
 * Request interface for creating a new user
 *
 * Omits the id, createdAt, and updatedAt fields as they are
 * generated by the system
 */
export interface CreateUserRequest {
  firstName: string;
  lastName: string;
  maidenName?: string;
  age: number;
  gender: "male" | "female" | "other";
  email: string;
  phone: string;
  username: string;
  password: string;
  birthDate: string;
  image: string;
  bloodGroup: string;
  height: number;
  weight: number;
  eyeColor: string;
  hair: {
    color: string;
    type: string;
  };
  domain: string;
  ip: string;
  address: {
    address: string;
    city: string;
    coordinates: {
      lat: number;
      lng: number;
    };
    postalCode: string;
    state: string;
  };
  macAddress: string;
  university: string;
  bank: {
    cardExpire: string;
    cardNumber: string;
    cardType: string;
    currency: string;
    iban: string;
  };
  company: {
    address: {
      address: string;
      city: string;
      coordinates: {
        lat: number;
        lng: number;
      };
      postalCode: string;
      state: string;
    };
    department: string;
    name: string;
    title: string;
  };
  ein: string;
  ssn: string;
  userAgent: string;
}

/**
 * Request interface for updating an existing user
 *
 * All fields are optional except id, and the id field is required
 * to identify which user to update
 */
export interface UpdateUserRequest extends Partial<CreateUserRequest> {
  id: number;
}

/**
 * Generic API response wrapper
 *
 * Standard response format for all API endpoints
 */
export interface ApiResponse<T> {
  data: T;
  message: string;
  success: boolean;
}

/**
 * Paginated response wrapper
 *
 * Used for endpoints that return paginated lists of data
 */
export interface PaginatedResponse<T> {
  data: T[];
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

/**
 * Common table filter parameters
 *
 * Used for search, pagination, and sorting across table components
 */
export interface TableFilters {
  search?: string;
  page?: number;
  limit?: number;
  sortBy?: string;
  sortOrder?: "asc" | "desc";
}

/**
 * Generic select option interface
 *
 * Used for dropdown and select components throughout the application
 */
export interface SelectOption {
  label: string;
  value: string | number;
}
